---
name: interview

channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=7.15.0
  - humanfriendly=4.18
  - jupyter=1.0.0
  - pandas=1.4.2
  - numpy=1.21.5
  - pip
  - pip:
    - pytest-watch==4.2.0
